import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <style>{`
        h1 {
          font-size: 3em;
          text-align: center;
          margin-top: 20px;
          color: #4a148c;
          text-shadow: 2px 2px 4px rgba(0,0,0,0.2);
          animation: fadeIn 2s ease-in;
        }
        .heart {
          color: #e91e63;
          font-size: 2em;
          display: inline-block;
          animation: pulse 1s infinite;
        }
      `}</style>
        <h1>
        Nuestro Amor a Través del Tiempo <span className="heart">♥</span>
        </h1>
        {children}
      </body>
    </html>
  );
}
